inhibit_all_warnings!
platform :ios, '8.0'

target :KDTUser do

pod 'SDCycleScrollView','~> 1.3'
pod 'UITableView+FDTemplateLayoutCell', '~> 1.4'
pod 'FMDB', '~> 2.5'
pod 'RXSDK','~> 1.0.4'
pod 'SDWebImage', '~> 3.7.3'
pod 'MJRefresh', '~> 3.0.6'
pod 'MJExtension', '~> 3.0.7'
pod 'SVProgressHUD', '~> 2.0-beta'
pod 'Masonry', '~> 0.6.3'
pod 'YYWebImage', '~> 0.9.11'

end
